### ISSUE TITLE
[OSX] make problems

### ISSUE THREAD

**Issue by markson14** [clancylian/retinaface#13]
Hi, 
just wondering does this project support MacOS system? thank you. BTW, this is a great work!

**Comment by clancylian** [comment]
hi, 
this project may not support on macOS, because it doesn't have GPU, and some env may different between ubuntu.

thanks.

**Comment by markson14** [comment]
> hi,
> this project may not support on macOS, because it doesn't have GPU, and some env may different between ubuntu.
> 
> thanks.

cheers
