### ISSUE TITLE
如何换成896*1280的分辨率

### ISSUE THREAD

**Issue by Jerry3062** [clancylian/retinaface#5]
您好，我测试了320*320的输入，感觉还是比较准确。但是当我将prototxt里输入改成1280*896之后，没有出来任何检测结果。请问如何将输入改到1280*896呢？谢谢整理和开源！

**Comment by clancylian** [comment]
你好，我这个是之前的实验版本，项目比较忙后续有空会改，如果你要改分辨率，应该是只要修改prototxt，但是在可执行文件下有个tensorRT的cache文件，这个是之前生成的必须删除。

**Comment by Jerry3062** [comment]
好的，谢谢指点。
