### ISSUE TITLE
I got some poor result using default model

### ISSUE THREAD

**Issue by jinfagang** [clancylian/retinaface#6]
![image](https://user-images.githubusercontent.com/21303438/65028562-d4b87880-d96e-11e9-9f3c-98f414fb2282.png)
![image](https://user-images.githubusercontent.com/21303438/65028586-dd10b380-d96e-11e9-82a9-175877335d31.png)

\
These pictures can not detect faces, also some tiny faces can not recognized either when test on videos.

Does any mistake on image preprocessing? or model not good enough? this shouldn't be retinaface performance.

**Comment by clancylian** [comment]
hi 
you should check your network input, in my prototxt, it just 320x320, you should use bigger input maybe 1920x1080. And if you understand the code, you can debug the image preprocessing by cv::imshow to see whether error occur.

**Comment by OPPOA113** [comment]
@clancylian 你好
我在Ubuntu系统下，cmake 选项只有tensorrt是ON，其他几个都是OFF。然后运行的时候，mnet-deconv-0517.prototxt中的宽高设置为320x320时，而且图像需要resize到320x320时，才会有检测结果，且不说这个检测效果如何【其实检测结果不太好】。然后prototxt里设置成其他的size输入，即使为1920x1080之后，不管图像resize为多少，都检测不到结果。。。。这是可能是因为啥？？？？

**Comment by swearos** [comment]
npp接口用错了，https://docs.nvidia.com/cuda/export/npp/group__image__geometry__transforms.html

将nppiResizeSqrPixel_8u_C3R 改为nppiResize_8u_C3R

**Comment by 394781865** [comment]
请问npp模式是什么？

**Comment by 394781865** [comment]
tensorrt version是什么？
