### ISSUE TITLE
请问是怎样优化的后处理时间呢?

### ISSUE THREAD

**Issue by guoguangchao** [clancylian/retinaface#7]
请问是怎样优化的后处理时间呢,这部分代码是在哪个文件中?谢谢

**Comment by clancylian** [comment]
你好， 你可以看下作者的python代码，我一开始是按照作者的代码逻辑改成c++的，但是python的一些逻辑和c++不太一样，比如python算个矩阵很容易，可以对多个候选框同时处理，但c++不行，所以后面我先做阈值判断，把大部分的阈值低的框先过滤掉了。总而言之就是语言特点不一样导致的，python并不会有这个问题，所以要说有优化也算，要说没优化也算。

**Comment by guoguangchao** [comment]
好的,谢谢~
